### ISSUE TITLE
Can it work on high level?

### ISSUE THREAD

**Issue by Magicgravel** [JonasFovea/go1controller#2]
I added this package to my codes, but it doesn't work for me. And it seem not support to high level.

**Comment by JonasFovea** [comment]
Have you tried the dev branch?
The main branch is currently not up to date.

The current setup is for the Logitech F130 gamepad.

You might have to tweak the mapping for your gamepad.

**Comment by JonasFovea** [comment]
I am closing this issue for now.
If you have further questions feel free to ask.
